
package com.nucleus.cfi.ws.client.stub.shortMessageService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "shortMessageService", targetNamespace = "http://www.nucleus.com/schemas/integration/ShortMessageService", wsdlLocation = "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/shortMessageService/shortMessageService.wsdl")
public class ShortMessageService
    extends Service
{

    private final static URL SHORTMESSAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.nucleus.cfi.ws.client.stub.shortMessageService.ShortMessageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.nucleus.cfi.ws.client.stub.shortMessageService.ShortMessageService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/shortMessageService/shortMessageService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/shortMessageService/shortMessageService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        SHORTMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public ShortMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ShortMessageService() {
        super(SHORTMESSAGESERVICE_WSDL_LOCATION, new QName("http://www.nucleus.com/schemas/integration/ShortMessageService", "shortMessageService"));
    }

    /**
     * 
     * @return
     *     returns ShortMessage
     */
    @WebEndpoint(name = "shortMessageSoap11")
    public ShortMessage getShortMessageSoap11() {
        return super.getPort(new QName("http://www.nucleus.com/schemas/integration/ShortMessageService", "shortMessageSoap11"), ShortMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ShortMessage
     */
    @WebEndpoint(name = "shortMessageSoap11")
    public ShortMessage getShortMessageSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nucleus.com/schemas/integration/ShortMessageService", "shortMessageSoap11"), ShortMessage.class, features);
    }

}
