
package com.nucleus.cfi.ws.client.stub.pushNotificationService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "pushNotification", targetNamespace = "http://www.nucleus.com/schemas/integration/PushNotificationService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PushNotification {


    /**
     * 
     * @param pushNotificationRequest
     * @return
     *     returns com.nucleus.cfi.ws.client.stub.pushNotificationService.PushNotificationResponse
     */
    @WebMethod
    @WebResult(name = "pushNotificationResponse", targetNamespace = "http://www.nucleus.com/schemas/integration/PushNotificationService", partName = "pushNotificationResponse")
    public PushNotificationResponse pushNotification(
        @WebParam(name = "pushNotificationRequest", targetNamespace = "http://www.nucleus.com/schemas/integration/PushNotificationService", partName = "pushNotificationRequest")
        PushNotificationRequest pushNotificationRequest);

}
