
package com.nucleus.cfi.ws.client.stub.communication.async;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "commAsyncService", targetNamespace = "http://www.nucleus.com/schemas/commAsyncService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CommAsyncService {


    /**
     * 
     * @param commAsyncRequest
     * @return
     *     returns com.nucleus.cfi.ws.client.stub.communication.async.CommAsyncResponse
     */
    @WebMethod
    @WebResult(name = "commAsyncResponse", targetNamespace = "http://www.nucleus.com/schemas/commAsyncService", partName = "commAsyncResponse")
    public CommAsyncResponse handleCommAsynchronously(
        @WebParam(name = "commAsyncRequest", targetNamespace = "http://www.nucleus.com/schemas/commAsyncService", partName = "commAsyncRequest")
        CommAsyncRequest commAsyncRequest);

}
