
package com.nucleus.cfi.ws.client.stub.communication.async;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "communicationAsyncService", targetNamespace = "http://www.nucleus.com/schemas/commAsyncService", wsdlLocation = "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/async/commAsyncService.wsdl")
public class CommunicationAsyncService
    extends Service
{

    private final static URL COMMUNICATIONASYNCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.nucleus.cfi.ws.client.stub.communication.async.CommunicationAsyncService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.nucleus.cfi.ws.client.stub.communication.async.CommunicationAsyncService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/async/commAsyncService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/async/commAsyncService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        COMMUNICATIONASYNCSERVICE_WSDL_LOCATION = url;
    }

    public CommunicationAsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CommunicationAsyncService() {
        super(COMMUNICATIONASYNCSERVICE_WSDL_LOCATION, new QName("http://www.nucleus.com/schemas/commAsyncService", "communicationAsyncService"));
    }

    /**
     * 
     * @return
     *     returns CommAsyncService
     */
    @WebEndpoint(name = "commAsyncServiceSoap11")
    public CommAsyncService getCommAsyncServiceSoap11() {
        return super.getPort(new QName("http://www.nucleus.com/schemas/commAsyncService", "commAsyncServiceSoap11"), CommAsyncService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CommAsyncService
     */
    @WebEndpoint(name = "commAsyncServiceSoap11")
    public CommAsyncService getCommAsyncServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nucleus.com/schemas/commAsyncService", "commAsyncServiceSoap11"), CommAsyncService.class, features);
    }

}
