CREATE TABLE ACCESS_LOG 
(	ID DECIMAL(19,0) NOT NULL, 
	REQUEST_DATE_TIME DATETIME2 (6), 
	METHOD VARCHAR(255), 
	MODULE VARCHAR(255), 
	QUERY_STRING VARCHAR(4000), 
	QUERY_STRING_FRAGMENT VARCHAR(4000), 
	REMOTEHOST VARCHAR(255), 
	SERVER_IP VARCHAR(255), 
	SESSION_ID VARCHAR(255), 
	URI VARCHAR(4000), 
	URI_FRAGMENT VARCHAR(4000), 
	USER_NAME VARCHAR(255), 
	STATUS_CODE BIGINT NOT NULL, 
	WEB_URI_REPOSITORY VARCHAR(255), 
	 PRIMARY KEY (ID)	 
);

