
package com.nucleus.cfi.ws.client.stub.mailMessageService;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "mailMessage", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MailMessage {


    /**
     * 
     * @param mailSendRequest
     * @return
     *     returns com.nucleus.cfi.ws.client.stub.mailMessageService.MailSendResponse
     */
    @WebMethod
    @WebResult(name = "mailSendResponse", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService", partName = "mailSendResponse")
    public MailSendResponse mailSend(
        @WebParam(name = "mailSendRequest", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService", partName = "mailSendRequest")
        MailSendRequest mailSendRequest);

    /**
     * 
     * @param deliveryReportRequest
     * @return
     *     returns com.nucleus.cfi.ws.client.stub.mailMessageService.DeliveryReportResponse
     */
    @WebMethod
    @WebResult(name = "deliveryReportResponse", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService", partName = "deliveryReportResponse")
    public DeliveryReportResponse deliveryReport(
        @WebParam(name = "deliveryReportRequest", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService", partName = "deliveryReportRequest")
        DeliveryReportRequest deliveryReportRequest);

}
