
package com.nucleus.cfi.ws.client.stub.mailMessageService;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "mailMessageService", targetNamespace = "http://www.nucleus.com/schemas/integration/MailMessageService", wsdlLocation = "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/mailMessageService/mailMessageService.wsdl")
public class MailMessageService
    extends Service
{

    private final static URL MAILMESSAGESERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.nucleus.cfi.ws.client.stub.mailMessageService.MailMessageService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.nucleus.cfi.ws.client.stub.mailMessageService.MailMessageService.class.getResource(".");
            url = new URL(baseUrl, "file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/mailMessageService/mailMessageService.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/D:/CAS/CurrentGA/FRAMEWORK/neutrino-core-project/neutrino-core-framework-integration/src/main/resources/ws/wsdl/mailMessageService/mailMessageService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        MAILMESSAGESERVICE_WSDL_LOCATION = url;
    }

    public MailMessageService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailMessageService() {
        super(MAILMESSAGESERVICE_WSDL_LOCATION, new QName("http://www.nucleus.com/schemas/integration/MailMessageService", "mailMessageService"));
    }

    /**
     * 
     * @return
     *     returns MailMessage
     */
    @WebEndpoint(name = "mailMessageSoap11")
    public MailMessage getMailMessageSoap11() {
        return super.getPort(new QName("http://www.nucleus.com/schemas/integration/MailMessageService", "mailMessageSoap11"), MailMessage.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailMessage
     */
    @WebEndpoint(name = "mailMessageSoap11")
    public MailMessage getMailMessageSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.nucleus.com/schemas/integration/MailMessageService", "mailMessageSoap11"), MailMessage.class, features);
    }

}
